name: Test And Publish Allure Report

on:
  push:
    branches: 
      - master

jobs: 
  test-and-report: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run automated tests
        run: npm run test:headless
      - name: Generate and publish test report
        if: ${{ always() }}
        run: npm run generate_test_report
        env: 
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: $ {{ secrets.NETLIFY_SITE_ID }}